name: Domination
main: littlegruz.domination.DomMain
version: 0.1

commands:
   addcapturepoint:
      description: Sets a region to be a capture point
      usage: /addcapturepoint <name>
   removecapturepoint:
      description: Removes a region from being a capture point
      usage: /removecapturepoint <name>

permissions:
   domination.capturepoints:
      description: Adding or removing capture points
      default: op

depends: [WorldGuard]